### ISSUE TITLE
ValueError of unknown layer in create_test_vcfs.sh

### ISSUE THREAD

**Issue by sophy7074** [mchowdh200/samplot-ml#2]
Dear @mchowdh200 ,

I'm trying to filter SV vcf with samplot-ml. But there is an error when running create_test_vcfs.sh. How to fix it?

The command I run is :
`bash create_test_vcfs.sh --model-path samplot-ml.h5 --data-list image-list.txt --vcf ../../vcf/HG002_SVs_Tier1_v0.6.deal.vcf --num-processes 5 --batch-size 100 --out-dir vcf_batch_100/`

The error log is :
2020-10-22 10:52:24.612032: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "{path}/samplot-ml/run.py", line 263, in <module>
    args.func(args)
  File "{path}/samplot-ml/run.py", line 44, in predict
    model = tf.keras.models.load_model(args.model_path)
  File "{path}/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 182, in load_mo
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "{path}/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 178, in 
    custom_objects=custom_objects)
  File "{path}/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in 
    return deserialize(config, custom_objects=custom_objects)
  File "{path}/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 175, i
    printable_module_name='layer')
  File "{path}/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 358, in
    list(custom_objects.items())))
  File "{path}/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2239, in fr
    config, custom_objects=custom_objects)
  File "{path}/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 617, in f
    config, custom_objects)
  File "{path}/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 1204, in 
    process_layer(layer_data)
  File "{path}/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 1186, in 
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "{path}/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 175, i
    printable_module_name='layer')
  File "{path}/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 347, in
    config, module_objects, custom_objects, printable_module_name)
  File "{path}/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 296, in
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: GeLU

Best wishes,
Tiany

**Comment by candiceleilani** [comment]
Having the same problem^

**Comment by mchowdh200** [comment]
I'm going to close this issue due to its age (sorry I never replied).  Since this issue was opened, I made a lot of changes to samplot-ml to prepare it for publication and rewrote the workflow to use snakemake to ensure all packages were at the correct version.  This pipeline should avoid errors like the one we see above, likely due to an incorrect version of TensorFlow.
